/*
 * Copyright © 2016-2017 VMware, Inc.  All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, without
 * warranties or conditions of any kind, EITHER EXPRESS OR IMPLIED.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */


[
    uuid (d12a2dce-6bb1-4190-8e3f-1c29f5508917),
    version(1.0),
    pointer_default(unique)
]

interface demo_privsep
{
#include "pmdrpctypes.h"

    unsigned32
    demo_privsep_rpc_version(
        [in] handle_t hBinding,
        [out] wstring_t* ppwszVersion
        );

    unsigned32
    demo_privsep_rpc_isprime(
        [in] handle_t hBinding,
        [in] signed32 nPrime,
        [out] signed32 *pnIsPrime
        );

    unsigned32
    demo_privsep_rpc_primes(
        [in] handle_t hBinding,
        [in] signed32 nStart,
        [in] signed32 nCount,
        [out] PINT_ARRAY *ppIntArray
        );
}
