/*
 * Copyright © 2016-2017 VMware, Inc.  All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, without
 * warranties or conditions of any kind, EITHER EXPRESS OR IMPLIED.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */


[
    uuid (aa17f964-7cac-4da8-a91c-1edae8412e00),
    version(1.0),
    pointer_default(unique)
]

interface netmgmt_privsep
{
#include "pmdrpctypes.h"
#include "netmgmtrpctypes.h"

    unsigned32
    netmgr_privsep_rpc_get_version(
        [in] handle_t hBinding,
        [out] wstring_t* pwszVersion
        );

    unsigned32
    netmgr_privsep_rpc_is_networkd_running(
        [in] handle_t hBinding,
        [out] wstring_t* pwszIsNetworkdRunning
        );

    /*
     * Interface configuration APIs
     */
    unsigned32
    netmgr_privsep_rpc_set_mac_addr(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [in] wstring_t pwszMacAddress
    );

    unsigned32
    netmgr_privsep_rpc_get_mac_addr(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [out] wstring_t *ppwszMacAddress
    );

    unsigned32
    netmgr_privsep_rpc_set_link_mode(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [in] NET_RPC_LINK_MODE linkMode
    );

    unsigned32
    netmgr_privsep_rpc_get_link_mode(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [out] NET_RPC_LINK_MODE *pLinkMode
    );

    unsigned32
    netmgr_privsep_rpc_set_link_mtu(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [in] unsigned32 mtu
    );

    unsigned32
    netmgr_privsep_rpc_configure(
        [in] handle_t hBinding,
        [in] PPMD_WSTRING_ARRAY pwszArgv
    );

    unsigned32
    netmgr_privsep_rpc_get_dhcp4_client_identifier(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [out] wstring_t *ppwszDHCP4ClientIndentifier
    );

    unsigned32
    netmgr_privsep_rpc_get_dhcp_mode(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [out] unsigned32 *pDHCPMode
    );

    unsigned32
    netmgr_privsep_rpc_get_dhcp_client_iaid(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [out] unsigned32 *pIaid
    );

    unsigned32
    netmgr_privsep_rpc_get_link_mtu(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [out] unsigned32 *pMtu
    );

    unsigned32
    netmgr_privsep_rpc_set_link_state(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [in] NET_RPC_LINK_STATE linkState
    );

    unsigned32
    netmgr_privsep_rpc_get_link_state(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [out] NET_RPC_LINK_STATE *pLinkState
    );

    unsigned32
    netmgr_privsep_rpc_ifup(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName
    );

    unsigned32
    netmgr_privsep_rpc_ifdown(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName
    );

    unsigned32
    netmgr_privsep_rpc_get_link_info(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [out] PNET_RPC_LINK_INFO_ARRAY *ppLinkInfoArray
    );


    /*
     * IP Address configuration APIs
     */
    unsigned32
    netmgr_privsep_rpc_set_ipv4_addr_gateway(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [in] NET_RPC_IPV4_ADDR_MODE mode,
        [in] wstring_t pwszIPv4AddrPrefix,
        [in] wstring_t pwszIPv4Gateway
    );

    unsigned32
    netmgr_privsep_rpc_get_ipv4_addr_gateway(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [out] NET_RPC_IPV4_ADDR_MODE *pMode,
        [out] wstring_t *ppwszIPv4AddrPrefix,
        [out] wstring_t *ppwszIPv4Gateway
    );

    unsigned32
    netmgr_privsep_rpc_add_static_ipv6_addr(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [in] wstring_t pwszIPv6AddrPrefix
    );

    unsigned32
    netmgr_privsep_rpc_delete_static_ipv6_addr(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [in] wstring_t pwszIPv6AddrPrefix
    );

    unsigned32
    netmgr_privsep_rpc_set_ipv6_addr_mode(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [in] unsigned32 enableDhcp,
        [in] unsigned32 enableAutoconf
    );

    unsigned32
    netmgr_privsep_rpc_get_ipv6_addr_mode(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [out] unsigned32 *pDhcpEnabled,
        [out] unsigned32 *pAutoconfEnabled
    );

    unsigned32
    netmgr_privsep_rpc_set_ipv6_gateway(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [in] wstring_t pwszIPv6Gateway
    );

    unsigned32
    netmgr_privsep_rpc_get_ipv6_gateway(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [out] wstring_t *ppwszIPv6Gateway
    );

    unsigned32
    netmgr_privsep_rpc_get_ip_addr(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [in] unsigned32 addrTypes,
        [out] NET_RPC_IP_ADDR_ARRAY **ppIpAddrArray
    );

    unsigned32
    netmgr_privsep_rpc_get_addresses(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [out] PPMD_WSTRING_ARRAY *ppwszAddresses
    );

    unsigned32
    netmgr_privsep_rpc_get_routes(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [out] PPMD_WSTRING_ARRAY *ppwszRoutes
    );


    /*
     * Route configuration APIs
     */
    unsigned32
    netmgr_privsep_rpc_add_static_ip_route(
        [in] handle_t hBinding,
        [in] NET_RPC_IP_ROUTE *pIpRoute
    );

    unsigned32
    netmgr_privsep_rpc_delete_static_ip_route(
        [in] handle_t hBinding,
        [in] NET_RPC_IP_ROUTE *pIpRoute
    );

    unsigned32
    netmgr_privsep_rpc_get_static_ip_routes(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [out] NET_RPC_IP_ROUTE_ARRAY **ppIpRouteArray
    );


    /*
     * DNS configuration APIs
     */
    unsigned32
    netmgr_privsep_rpc_add_dns_server(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [in] wstring_t pwszDnsServer
    );

    unsigned32
    netmgr_privsep_rpc_delete_dns_server(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [in] wstring_t pwszDnsServer
    );

    unsigned32
    netmgr_privsep_rpc_set_dns_servers(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [in] NET_RPC_DNS_MODE dwMode,
        [in] PPMD_WSTRING_ARRAY pwszDnsServers
    );

    unsigned32
    netmgr_privsep_rpc_get_dns_servers(
        [in] handle_t hBinding,
        [out] PPMD_WSTRING_ARRAY *ppwszDnsServers
    );

    unsigned32
    netmgr_privsep_rpc_add_dns_domain(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [in] wstring_t pwszDnsDomain
    );

    unsigned32
    netmgr_privsep_rpc_delete_dns_domain(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [in] wstring_t pwszDnsDomain
    );

    unsigned32
    netmgr_privsep_rpc_set_dns_domains(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [in] PPMD_WSTRING_ARRAY pwszDnsDomains
    );

    unsigned32
    netmgr_privsep_rpc_get_dns_domains(
        [in] handle_t hBinding,
        [out] PPMD_WSTRING_ARRAY *ppwszDnsDomains
    );


    /*
     * DHCP options, DUID, IAID configuration APIs
     */
    unsigned32
    netmgr_privsep_rpc_set_iaid(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [in] unsigned32 dwIaid
    );

    unsigned32
    netmgr_privsep_rpc_get_iaid(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [out] unsigned32 *pdwIaid
    );

    unsigned32
    netmgr_privsep_rpc_set_duid(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [in] wstring_t pwszDuid
    );

    unsigned32
    netmgr_privsep_rpc_get_duid(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [out] wstring_t *ppwszDuid
    );

    /*
     * ntp APIs
     */
    unsigned32
    netmgr_privsep_rpc_get_ntp_servers(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [out] PPMD_WSTRING_ARRAY *ppwszNtpServers
    );

    unsigned32
    netmgr_privsep_rpc_set_ntp_servers(
        [in] handle_t hBinding,
        [in] PPMD_WSTRING_ARRAY pwszNtpServers
    );

    unsigned32
    netmgr_privsep_rpc_add_ntp_servers(
        [in] handle_t hBinding,
        [in] PPMD_WSTRING_ARRAY pwszNtpServers
    );

    unsigned32
    netmgr_privsep_rpc_delete_ntp_servers(
        [in] handle_t hBinding,
        [in] PPMD_WSTRING_ARRAY pwszNtpServers
    );

    /*
     * nft APIs
     */
    unsigned32
    netmgr_privsep_rpc_nft_get_tables(
        [in] handle_t hBinding,
        [in] wstring_t pwszFamily,
        [in] wstring_t pwszTable,
        [out] PPMD_WSTRING_ARRAY *ppwszNftables
    );

    unsigned32
    netmgr_privsep_rpc_nft_get_chains(
        [in] handle_t hBinding,
        [in] wstring_t pwszFamily,
        [in] wstring_t pwszTable,
        [in] wstring_t pwszChains,
        [out] PPMD_WSTRING_ARRAY *ppwszNftablesChains
    );

    unsigned32
    netmgr_privsep_rpc_get_nft_rules(
        [in] handle_t hBinding,
        [in] wstring_t pwszTable,
        [out] wstring_t *ppwszNftableRules
    );

    /*
     * Misc APIs
     */
    unsigned32
    netmgr_privsep_rpc_set_hostname(
        [in] handle_t hBinding,
        [in] wstring_t pwszHostname
    );

    unsigned32
    netmgr_privsep_rpc_get_hostname(
        [in] handle_t hBinding,
        [out] wstring_t *ppwszHostname
    );

    unsigned32
    netmgr_privsep_rpc_wait_for_link_up(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [in] unsigned32 dwTimeout
    );

    unsigned32
    netmgr_privsep_rpc_wait_for_ip(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [in] unsigned32 dwTimeout,
        [in] NET_RPC_ADDR_TYPE dwAddrTypes
    );

    unsigned32
    netmgr_privsep_rpc_get_error_info(
        [in] handle_t hBinding,
        [in] unsigned32 nmErrCode,
        [out] wstring_t *ppwszErrInfo
    );

    unsigned32
    netmgr_privsep_rpc_set_network_param(
        [in] handle_t hBinding,
        [in] wstring_t pwszObjectName,
        [in] wstring_t pwszParamName,
        [in] wstring_t pwszParamValue
    );

    unsigned32
    netmgr_privsep_rpc_get_network_param(
        [in] handle_t hBinding,
        [in] wstring_t pwszObjectName,
        [in] wstring_t pwszParamName,
        [out] wstring_t *ppwszParamValue
    );

    unsigned32
    netmgr_privsep_rpc_get_system_status(
        [in] handle_t hBinding,
        [out] wstring_t *ppwszSystemStatus
    );

    unsigned32
    netmgr_privsep_rpc_get_link_status(
        [in] handle_t hBinding,
        [in] wstring_t pwszInterfaceName,
        [out] wstring_t *ppwszLinkStatus
    );
}
