/*
 * Copyright © 2016-2017 VMware, Inc.  All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, without
 * warranties or conditions of any kind, EITHER EXPRESS OR IMPLIED.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */


[
    uuid (ae35fbcb-81dd-4446-83c6-b74f8d46e025),
    version(1.0),
    pointer_default(unique)
]

interface pkg_privsep
{
#include <lw/types.h>
#include "pmdrpctypes.h"
#include "pkgmgmtrpctypes.h"

typedef [context_handle] void *pkg_privsep_handle_t;

    unsigned32
    pkg_privsep_rpc_open_handle(
        [in] handle_t hBinding,
        [in] PTDNF_RPC_CMD_ARGS pArgs,
        [out] pkg_privsep_handle_t *phPkgHandle
        );

    unsigned32
    pkg_privsep_rpc_version(
        [in] handle_t hBinding,
        [out] wstring_t *ppwszVersion
        );

    unsigned32
    pkg_privsep_rpc_count(
        [in] handle_t hBinding,
        [in] pkg_privsep_handle_t hPkgHandle,
        [out] unsigned32 *pdwCount
        );

    unsigned32
    pkg_privsep_rpc_info(
        [in] handle_t hBinding,
        [in] pkg_privsep_handle_t hPkgHandle,
        [in] unsigned32 nScope,
        [in] PPMD_WSTRING_ARRAY pPkgNameSpecs,
        [out] PTDNF_RPC_PKGINFO_ARRAY *ppInfo
        );

    unsigned32
    pkg_privsep_rpc_list(
        [in] handle_t hBinding,
        [in] pkg_privsep_handle_t hPkgHandle,
        [in] unsigned32 nScope,
        [in] PPMD_WSTRING_ARRAY pPkgNameSpecs,
        [out] PTDNF_RPC_PKGINFO_ARRAY *ppInfo
        );

    unsigned32
    pkg_privsep_rpc_repolist(
        [in] handle_t hBinding,
        [in] pkg_privsep_handle_t hPkgHandle,
        [in] unsigned32 nFilter,
        [out] PTDNF_RPC_REPODATA_ARRAY *ppRepoData
        );

    unsigned32
    pkg_privsep_rpc_updateinfo_summary(
        [in] handle_t hBinding,
        [in] pkg_privsep_handle_t hPkgHandle,
        [out] PTDNF_RPC_UPDATEINFO_SUMMARY_ARRAY *ppUpdateInfoSummary
        );

    unsigned32
    pkg_privsep_rpc_resolve(
        [in] handle_t hBinding,
        [in] pkg_privsep_handle_t hPkgHandle,
        [in] unsigned32 nAlterType,
        [out] PTDNF_RPC_SOLVED_PKG_INFO *ppSolvedPkgInfo
        );

    unsigned32
    pkg_privsep_rpc_alter(
        [in] handle_t hBinding,
        [in] pkg_privsep_handle_t hPkgHandle,
        [in] unsigned32 nAlterType
        );

    unsigned32
    pkg_privsep_rpc_get_error_string(
        [in] handle_t hBinding,
        [in] unsigned32 dwErrorCode,
        [out] wstring_t *ppwszErrorString
        );
}
