/*
 * Copyright © 2016-2017 VMware, Inc.  All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, without
 * warranties or conditions of any kind, EITHER EXPRESS OR IMPLIED.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */


[
    uuid (3ee131de-2fc1-41fa-b06b-0387ee2296c9),
    version(1.0),
    pointer_default(unique)
]

interface privsepd
{
#include "pmdrpctypes.h"

    unsigned32
    privsepd_rpc_basic_auth(
        [in] handle_t hBinding,
        [in] wstring_t pwszBasic,
        [in] wstring_t pwszContext,
        [out] unsigned32 *pnValid
        );

    unsigned32
    privsepd_rpc_unix_auth(
        [in] handle_t hBinding,
        [in] wstring_t pwszUser,
        [out] wstring_t *ppszUnixSalt,
        [out] wstring_t *ppszB64SValue,
        [out] wstring_t *ppszB64VValue
    );
}
